import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { CreateStaffUserInput, UpdateStaffMemberInput } from '@car-rental/shared';
import * as bcrypt from 'bcrypt';
import { randomInt } from 'node:crypto';
import { AuditService } from '../../audit/audit.service';
import { AuthService } from '../../auth/auth.service';
import { PrismaService } from '../../prisma/prisma.service';
import { PrismaClientKnownRequestError } from '../../prisma/prisma-errors';
import { JwtUser } from '../../auth/types';
import { assertSameCompany, effectiveListCompanyFilter, isAdmin } from '../../auth/company-access';

const TEMP_LOWER = 'abcdefghjkmnpqrstuvwxyz';
const TEMP_UPPER = 'ABCDEFGHJKMNPQRSTUVWXYZ';
const TEMP_DIGIT = '23456789';
const TEMP_SPECIAL = '!@#$%^&*';

/** A2: matches shared `strongPasswordSchema` (length + character classes). */
function generateTemporaryPassword(): string {
  const length = 16;
  const pick = (alphabet: string) => alphabet[randomInt(alphabet.length)]!;
  const chars: string[] = [
    pick(TEMP_LOWER),
    pick(TEMP_UPPER),
    pick(TEMP_DIGIT),
    pick(TEMP_SPECIAL),
  ];
  const all = TEMP_LOWER + TEMP_UPPER + TEMP_DIGIT + TEMP_SPECIAL;
  for (let i = chars.length; i < length; i++) {
    chars.push(pick(all));
  }
  for (let i = chars.length - 1; i > 0; i--) {
    const j = randomInt(i + 1);
    const a = chars[i]!;
    const b = chars[j]!;
    chars[i] = b;
    chars[j] = a;
  }
  return chars.join('');
}

@Injectable()
export class StaffService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
    private readonly auth: AuthService,
  ) {}

  async create(
    body: CreateStaffUserInput,
    actor: JwtUser,
    reqCtx?: { ip?: string; userAgent?: string },
  ) {
    if (!isAdmin(actor)) {
      throw new ForbiddenException('Only admin can create staff users');
    }
    effectiveListCompanyFilter(actor, body.companyId);
    const [company, stationOk] = await Promise.all([
      this.prisma.company.findUnique({ where: { id: body.companyId } }),
      body.stationId
        ? this.prisma.station.findFirst({ where: { id: body.stationId, companyId: body.companyId } })
        : Promise.resolve({ id: 'skip' } as { id: string }),
    ]);
    if (!company) {
      throw new NotFoundException(`Company not found: ${body.companyId}`);
    }
    if (body.stationId && !stationOk) {
      throw new BadRequestException('Station does not belong to this company');
    }
    const email = body.email.toLowerCase().trim();
    const invite = body.sendInviteEmail === true;
    if (invite && !this.auth.staffInviteEmailConfigured()) {
      throw new BadRequestException(
        'Cannot send staff invite: configure SMTP (e.g. SMTP_HOST, SMTP_FROM) and APP_PUBLIC_BASE_URL',
      );
    }
    const hasPassword = body.password != null && body.password !== '';
    const plainPassword: string = hasPassword ? body.password! : generateTemporaryPassword();
    const autoGenerated = !hasPassword;
    const passwordHash = await bcrypt.hash(plainPassword, 10);
    let created;
    try {
      created = await this.prisma.user.create({
        data: {
          email,
          passwordHash,
          firstName: body.firstName.trim(),
          lastName: body.lastName.trim(),
          companyId: body.companyId,
          stationId: body.stationId ?? null,
          role: body.role,
        },
        select: {
          id: true,
          email: true,
          firstName: true,
          lastName: true,
          role: true,
          stationId: true,
          isActive: true,
          lastLoginAt: true,
          createdAt: true,
          homeStation: { select: { id: true, name: true, code: true } },
        },
      });
    } catch (e) {
      if (e instanceof PrismaClientKnownRequestError && e.code === 'P2002') {
        throw new ConflictException('Email already in use');
      }
      throw e;
    }
    await this.audit.log({
      userId: actor.sub,
      action: 'staff.create',
      entity: 'User',
      entityId: created.id,
      metadata: {
        email: created.email,
        role: created.role,
        companyId: body.companyId,
        temporaryPasswordGenerated: autoGenerated,
        inviteEmailSent: invite,
      },
    });
    if (invite) {
      try {
        await this.auth.sendStaffInviteSetupEmail(created.id, {
          actorUserId: actor.sub,
          ip: reqCtx?.ip,
          userAgent: reqCtx?.userAgent,
        });
      } catch (e) {
        await this.prisma.user.delete({ where: { id: created.id } });
        throw e;
      }
      return { ...created, inviteEmailSent: true as const };
    }
    if (autoGenerated) {
      return { ...created, temporaryPassword: plainPassword };
    }
    return created;
  }

  findAll(companyId: string | undefined, user: JwtUser) {
    const f = effectiveListCompanyFilter(user, companyId);
    return this.prisma.user.findMany({
      where: Object.keys(f).length ? f : undefined,
      orderBy: [{ lastName: 'asc' }, { email: 'asc' }],
      select: {
        id: true,
        email: true,
        firstName: true,
        lastName: true,
        role: true,
        stationId: true,
        isActive: true,
        lastLoginAt: true,
        createdAt: true,
        homeStation: { select: { id: true, name: true, code: true } },
      },
    });
  }

  /**
   * H2: resend `/auth/reset-password?token=…` for an existing staff user who has never logged in
   * (same mail path as create+invite). Requires SMTP + APP_PUBLIC_BASE_URL.
   */
  async sendSetupInviteEmail(
    targetId: string,
    actor: JwtUser,
    reqCtx?: { ip?: string; userAgent?: string },
  ): Promise<void> {
    if (!isAdmin(actor)) {
      throw new ForbiddenException('Only admin can resend staff setup emails');
    }
    const target = await this.prisma.user.findUnique({ where: { id: targetId } });
    if (!target) {
      throw new NotFoundException(`User not found: ${targetId}`);
    }
    assertSameCompany(actor, target.companyId, `User not found: ${targetId}`);
    if (targetId === actor.sub) {
      throw new BadRequestException('Cannot send setup email to yourself');
    }
    if (!target.isActive) {
      throw new BadRequestException('Cannot send setup email to an inactive user');
    }
    if (target.lastLoginAt != null) {
      throw new BadRequestException(
        'This user has already signed in — use Forgot password instead of a setup email',
      );
    }
    if (!this.auth.staffInviteEmailConfigured()) {
      throw new BadRequestException(
        'Cannot send staff invite: configure SMTP (e.g. SMTP_HOST, SMTP_FROM) and APP_PUBLIC_BASE_URL',
      );
    }
    await this.auth.sendStaffInviteSetupEmail(targetId, {
      actorUserId: actor.sub,
      ip: reqCtx?.ip,
      userAgent: reqCtx?.userAgent,
    });
  }

  async update(targetId: string, body: UpdateStaffMemberInput, user: JwtUser) {
    if (!isAdmin(user)) {
      throw new ForbiddenException('Only admin can update staff');
    }
    const target = await this.prisma.user.findUnique({ where: { id: targetId } });
    if (!target) {
      throw new NotFoundException(`User not found: ${targetId}`);
    }
    assertSameCompany(user, target.companyId, `User not found: ${targetId}`);
    if (targetId === user.sub) {
      if (body.isActive === false) {
        throw new ForbiddenException('Cannot deactivate your own account');
      }
      if (body.role !== undefined && body.role !== 'ADMIN') {
        throw new ForbiddenException('Cannot change your own role away from ADMIN');
      }
    }
    if (body.stationId !== undefined && body.stationId !== null) {
      const st = await this.prisma.station.findFirst({
        where: { id: body.stationId, companyId: target.companyId },
      });
      if (!st) {
        throw new BadRequestException('Station does not belong to this company');
      }
    }
    const activeAdmins = await this.prisma.user.count({
      where: { companyId: target.companyId, role: 'ADMIN', isActive: true },
    });
    if (target.role === 'ADMIN' && activeAdmins <= 1) {
      if (body.role !== undefined && body.role !== 'ADMIN') {
        throw new BadRequestException('Cannot change the only active admin’s role');
      }
      if (body.isActive === false) {
        throw new BadRequestException('Cannot deactivate the only active admin');
      }
    }
    const data: { role?: typeof target.role; stationId?: string | null; isActive?: boolean } = {};
    if (body.role !== undefined) {
      data.role = body.role;
    }
    if (body.stationId !== undefined) {
      data.stationId = body.stationId;
    }
    if (body.isActive !== undefined) {
      data.isActive = body.isActive;
    }
    return this.prisma.user.update({
      where: { id: targetId },
      data,
      select: {
        id: true,
        email: true,
        firstName: true,
        lastName: true,
        role: true,
        stationId: true,
        isActive: true,
        lastLoginAt: true,
        createdAt: true,
        homeStation: { select: { id: true, name: true, code: true } },
      },
    });
  }
}
